export const TEXTS = {
  home: {
    title: "Lego minifigs mystery box",
    buttonLabel: "Let's go!",
    buttonLabelLoading: "Loading...",
    error: "Something went wrong. Refresh page and try again please.",
  },
  selection: {
    title: "Choose your minifig",
    buttonLabel: "Proceed to shipment",
    showDetails: "Show details",
  },
  shipping: {
    title: "Shipping details",
    buttonLabel: "Submit",
    error: "Something went wrong",
    labels: {
      name: "Name",
      surname: "Surname",
      phoneNumber: "Phone number",
      email: "Email",
      dateOfBirth: "Date of birth",
      address: "Address",
      city: "City",
      state: "State",
      zipCode: "Zip code",
    },
    summary: "Summary",
  },
};

export const STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
